# SSE and HTTPS configuration for nginx and mummyDS on localhost
# Replace <SERVERNAME> with your domainname name

server {
    server_name <SERVERNAME>;

    # Allgemeine Komprimierung (Gzip)
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml text/event-stream; # text/event-stream ist wichtig für SSE
    gzip_min_length 1000;
    gzip_vary on;

    location / {
        proxy_pass http://127.0.0.1:8080; # Port of mummyDS
        proxy_http_version 1.1;
        proxy_set_header Connection ""; # important for Keep-Alive
        
        # SSE-spezifische Einstellungen
        proxy_buffering off;             # deaktivate buffering. data send directly
        proxy_cache off;                 # no caching
        chunked_transfer_encoding off;   # optional, sometimes helpful for SSE stability
        proxy_read_timeout 24h;          # prevents connection close for long sessions
        
        # Header for Backend-Server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Proxy-Frontend "nginx";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<SERVERNAME>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<SERVERNAME>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = <SERVERNAME>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name <SERVERNAME>;
    return 404; # managed by Certbot
}
